### ISSUE TITLE
error on install rhoban/rhio

### ISSUE THREAD

**Issue by haritsahm** [Rhoban/workspace#2]
what does this means?
sh: 1: cd: can't cd to src/rhoban/rhio
fatal: Not a git repository (or any of the parent directories): .git

**Comment by Gregwar** [comment]
Hello,
What are you trying to do?

**Comment by Gregwar** [comment]
We are moving to the catkin build system, if you want to build RhIO you can clone this repository and:

    ./workspace setup
    ./workspace install rhoban/rhio
    ./workspace build

**Comment by Gregwar** [comment]
Your message error is likely because workspace uses SSH to clone the remotes, you should register your RSA key with GitHub to get it working
